### ISSUE TITLE
Works with linux and ARM?

### ISSUE THREAD

**Issue by mgarciate** [megahertz/electron-simple-updater#32]
Hi, I wonder if **electron-simple-updater** is able to auto update an application running on **Linux with ARM** architecture (raspberry pi 3). Thank you in advance.

**Comment by megahertz** [comment]
I'm not sure. I think it should work. But electron-simple-publisher doesn't support arm, so you need to create updates manually.  I can add ARM support to electron-simple-publisher, but I need help for that because I have no such a device for tests.

**Comment by mgarciate** [comment]
Alright, I'll try it and let you know if I success. Thx

**Comment by megahertz** [comment]
Feel free to reopen this issue if it doesn't work.

**Comment by Kph1108** [comment]
I'm wondering if this issue was ever resolved. When you say create or publish manually how would I go about doing this? I'm trying to plublish on a arm architecture running 18.04 ubuntu and am running into an error publishing. I can publish with no issue on x86 desktop, but when I pull my code on the arm architecture it will not publish.
