### ISSUE TITLE
NSIS Support

### ISSUE THREAD

**Issue by Funisaac** [megahertz/electron-simple-updater#68]
Could you please add NSIS support?
If you already do, or if you won't add it, some info would be nice 😄

**Comment by megahertz** [comment]
I'm not going to support NSIS at this moment. It's better to use electron-updater if you need that.

**Comment by Funisaac** [comment]
Ok, thank you for the quick response!
May I ask why you've decided upon that?

**Comment by megahertz** [comment]
It's not a competitor of electron-updater, it's just an alternative option for those who needs some specific requirements. So, I'm not going to implement all the features of electron-updater. At least, I have no time resources for it. Since electron has no built-in support of NSIS, this task is pretty time consuming, instead of Squirrel which is built-in.  So a new target will make the package maintenance much harder.
